export const ICONLABEL = {
  accessible: "accessible",
  add: "add",
  car: "car",
  danger: "danger",
  event: "event",
  food: "food",
  garbage: "garbage",
  graffiti: "graffiti",
  home: "home",
  mapLogo: "mapLogo",
  mapMarker: "mapMarker",
  mapSign: "mapSign",
  message: "message",
  music: "music",
  nature: "nature",
  menu: "menu",
  parking: "parking",
  pet: "pet",
  school: "school",
  settings: "settings",
  starEmpty: "emptyStar",
  starFilled: "filledStar",
  townhall: "townhall",
  water: "water"
};
