#!/bin/bash

docker tag blueoceanhr/production:latest 351788166609.dkr.ecr.us-east-2.amazonaws.com/amplifyaustin:latest
docker push 351788166609.dkr.ecr.us-east-2.amazonaws.com/blueoceanhr/production:latest
